### ISSUE TITLE
How are we going to present?

### ISSUE THREAD

**Issue by InspectorConstructor** [UMLComputerGraphics/GraphicsProject#105]
I've never presented code before!

Are we each going to talk about out contributions while demoing?
Discuss the issues that arose?
In any pre-determined order?
Show our source?

**Comment by nickavv** [comment]
@InspectorConstructor are you sure we're set on this one? Maybe we should practice our presentation one more time ;)

**Comment by curran** [comment]
I would watch :)

Screenshots in the Readme would be great. Can y'all even still run this?

**Comment by InspectorConstructor** [comment]
It worked with a few changes in 2016 on my macbook, but I don't think the latest macOS has OpenGL support...

**Comment by emeralddusk** [comment]
What a bizarre email to get this morning.

I'm surprised you still had this open for so long.
Up late making last minute adjustments? haha

**Comment by nuclearmistake** [comment]
Lol... That's wild... I compiled these a few weeks ago for giggles.

Had to kill the -mt from boost libs and switch imagemagick to graphicsmagick and add a call to graphicsmagick::init in the texture loader, BUT ran fine after that.

**Comment by jnsnow** [comment]
lol. I hope everyone is doing well!

**Comment by nuclearmistake** [comment]
No u :-P

Code still compiles... Just need to use graphicsmagick and call
graphicsmagick.init when you initialize textures.
